version: '3.4'

services:
  audit.application:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44333
      - ConnectionStrings__AuditDBConnection=Server=sql.data,1433;Initial Catalog=AuditDB;Persist Security Info=False;User ID=sa;Password=P@ssw0rd; MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=10;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=test1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
    ports:
      - "56969:80"
      - "44333:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  compute.application:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44301
      - ConnectionStrings__ComputeDBConnection=Server=sql.data,1433;Initial Catalog=ComputeDB;Persist Security Info=False;User ID=sa;Password=P@ssw0rd;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=10;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=test1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
      - AuditServiceUri=http://audit.application:80
    ports:
      - "55348:80"
      - "44301:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
